[true == parse [1][integer!]]
[false == parse [1][word!]]
[true == parse "<a>" [<A>]]
[false == parse/case "<a>" [<A>]]
[true == parse "ab" ["a" ["b"]]]
[true == parse [a b] ['a ['b]]]
[parse "abc" [copy a 2 skip] a == "ab"]
[parse [a b c] [copy a 2 skip] a == [a b]]
